services:
  app:
    image: questqwe123/docker-project-74
    build:
      context: ./app
      dockerfile: Dockerfile.production
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ./app/services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
