name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./app/package-lock.json
      - run: make setup
        working-directory: ./app/app
      - run: make lint
        working-directory: ./app/app
      - run: make test
        working-directory: ./app/app
